# Themes related configurations
fonts:
  family: "Arial, sans-serif"
  title_size: "20px"
  label_size: "14px"
  small_size: "11px"

colors:
  primary: "#007BFF"
  background: "#FFFFFF"
  border: "#ccc"
  match_opacity: 0.3
  match_color: 'rgba(0, 123, 255, 0.3)'

layout:
  preview_height: 60
  preview_card_height: 90


# data related configuration
series:
  window_size: 30